model_name_or_path: facebook/nllb-200-3.3B
data_path: ./training_data/remapped_onlytags
encoder_decoder_type: nllb

use_peft: true
lora_rank: 16
unfrozen_layers: layers.23

do_train: true
do_eval: true
eval_strategy: steps
do_predict: true
language_pairs: de-en
load_best_model_at_end: false
save_only_model: true

low_cpu_mem_usage: true
bf16: true

learning_rate: 0.001
weight_decay: 0.01
gradient_accumulation_steps: 2
lr_scheduler_type: inverse_sqrt
warmup_ratio: 0.05

ignore_pad_token_for_loss: true
ignore_prompt_token_for_loss: true

per_device_train_batch_size: 8
per_device_eval_batch_size: 8

eval_steps: 0.05
save_strategy: steps
save_steps: 0.1
save_total_limit: 1

logging_strategy: steps
logging_steps: 0.05

output_dir: ./outputs/xml/remapped_onlytags/nllb-3b-freeze
num_train_epochs: 1

wandb_project_name: markup-tl
wandb_run_name: nllb-3b-remapped-onlytags-freeze

predict_with_generate: true
prediction_loss_only: true
max_new_tokens: 256
max_source_length: 256

seed: 42
overwrite_output_dir: true
num_beams: 5
ddp_timeout: 999999
report_to: wandb
overwrite_cache: true
